name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.8
        env:          
          POSTGRES_USER: "maglev"
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn-${{ matrix.node-version }}

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          MAGLEV_APP_DATABASE_USERNAME: "maglev"
          MAGLEV_APP_DATABASE_PASSWORD: "password"
        run: |
          bin/rails db:setup

      - name: Run Rails tests
        env:
          MAGLEV_APP_DATABASE_USERNAME: "maglev"
          MAGLEV_APP_DATABASE_PASSWORD: "password"
        run: bundle exec rspec

      - name: Run Javascript tests
        run: yarn test